.\"=====================================================================
.\" SBChroot - Setup and manage a chroot
.\" Copyright (c) 2007-2008, Michiel van Wessem, Manchester, United Kingdom
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\" * Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"=====================================================================
.TH SBCHROOT 8 2012-01-31 sbchroot-2.8.3 ""
.\"=====================================================================
.SH NAME
SBChroot \- The
.B Slackware
chroot tool for running multiple
.B Slackware Linux
guests
.\"=====================================================================
.SH SYNOPSIS
.B SBChroot
.RI [ options ]
.PP
-? -h --help -v --version
.PP
-s --start
.PP
-c --create -i --install
-r --rebuild
.PP
--clear --clean --clean-system
-rc --conf --config
-u --update -p --patch
.PP
--wipe --remove
.\"=====================================================================
.SH DESCRIPTION
.B SBChroot
is a tool that simplifies and automates the creates of
`full install' changeroots for
.B Slackware Linux.
.SS Instructions
The script assumes the presence of a mirror on the local system from
which it can install.
.PP
If you like to submit a patch, bugfix etc. The preferred method is
to clone my code on
.B github
and ammend the code and submit a pull request. Failing that ..
please email patches in a full unified diff format (diff -Naur) only.
.PP
.B SBChroot
must be run as root since it requires access to certain root-only functions
in order to setup the proper environment.
.\"=====================================================================
.SH OPTIONS
.TP 5
.B \-c, \--create
Create the chroot enviroment. This will create the directories,
and install the needed files (up and including to the latest patches)
as well as do an initial configuration.
.\"=====================================================================
.TP
.B \--clear, \--clean, \--clean-system
.B *EXPERIMENTAL*
This should remove any obviously non standard packages
from your system. At the moment the code is purely geared to SBo
related packages.
.\"=====================================================================
.TP
.B \-h, \-?, \--help
You're looking at it. This is the help you're looking for.  Yah. RLY.
.\"=====================================================================
.TP
.B \-i, \--install
Same as -c/--create
.\"=====================================================================
.TP
.B \-p, \--patch
Upgrade the chroot with the lastest patches. This will look at the patches/
directory in the local mirror and see if there have been any updated packages
that need to be installed,
.\"=====================================================================
.TP
.B \-r, \--rebuild
Rebuild the chroot. This will first wipe it, then rebuild it.
.B Note:
This doesn't allow automated removal due to the way the delete function works
(at the moment).
.\"=====================================================================
.TP
.B \-rc, \--config, \--conf
Redo the initial configuration steps.
.\"=====================================================================
.TP
.B \--remove
Remove the chroot. This will *delete* your chroot. Don't come
whining to me. It has plenty of prompts to stop you from doing
something intentional stupid.
.\"=====================================================================
.TP
.B \-s, \--start
The default action. This will also happen when SBChroot is called
without any default arguments.
.\"=====================================================================
.TP
.B \-u, \--update
Same as -r/--rebuild
.\"=====================================================================
.TP
.B \-v, \--version
Display the version of the current script.
.\"=====================================================================
.TP
.B \--wipe
Same as --remove
.\"=====================================================================
.SH AUTHOR
Michiel van Wessem, Leicester, United Kingdom
.\"=====================================================================
.SH SEE ALSO
chroot(1)
.TP
Slackware Linux website at 
.I http://www.slackware.com
.\"=====================================================================
